name 'zookeeper-cluster'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Application cookbook which installs and configures a Zookeeper cluster.'
long_description 'Application cookbook which installs and configures a Zookeeper cluster.'
version '1.0.0'

supports 'ubuntu', '>= 12.04'
supports 'centos', '>= 6.6'
supports 'redhat', '>= 6.6'

depends 'java'
depends 'libartifact', '~> 1.3'
depends 'poise', '~> 2.0'
depends 'poise-service'
depends 'selinux'
